export default Location=[
    {
        id:1,
        city: 'Lahore',
        dateTime: '07:50 PM - Wednesday, 31 januarry 2022',
        temprature: '13\u2103',
        weatherType: 'Night',
        wind: 14,
        rain: 50,
        humidity: 70,
    },
    {
        id:2,
        city: 'Karachi',
        dateTime: '06:30 PM - Friday, 1 Feb 2022',
        temprature: '15\u2103',
        weatherType: 'Cloudy',
        wind: 40,
        rain: 35,
        humidity: 30,
    },
    {
        id:3,
        city: 'Islamabad',
        dateTime: '10:30 PM - Sunday, 3 March 2022',
        temprature: '21\u2103',
        weatherType: 'Sunny',
        wind: 30,
        rain: 69,
        humidity: 65,
    },
    {
        id:4,
        city: 'Zam Studios',
        dateTime: '03:40 PM - Saturday, 15 januarry 2022',
        temprature: '10\u2103',
        weatherType: 'Rainy',
        wind: 78,
        rain: 99,
        humidity: 30,
    },
];